development:
  adapter: postgresql
  database: va_claims_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: va_claims_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: va_claims_production
  pool: 5
  timeout: 5000